[workspace]
members = [
    "rust/geodatafusion-flatgeobuf",
    "rust/geodatafusion-geojson",
    "rust/geodatafusion-geoparquet",
    "rust/geodatafusion",
]
exclude = ["python"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/datafusion-contrib/datafusion-geo"
rust-version = "1.85"
categories = ["science::geo"]

[workspace.dependencies]
approx = "0.5.1"
arrow-arith = "56"
arrow-array = "56"
arrow-schema = "56"
async-trait = "0.1"
datafusion = "50"
datafusion-datasource = "50"
datafusion-datasource-parquet = "50"
flatgeobuf = { version = "5.0", default-features = false }
futures = "0.3"
geo = "0.31.0"
geo-traits = "0.3.0"
geoarrow-array = "0.5"
geoarrow-flatgeobuf = "0.5"
geoarrow-geo = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f", version = "0.5" }
geoarrow-geojson = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoarrow-schema = "0.5"
geodatafusion = { path = "rust/geodatafusion" }
geohash = "0.13.1"
geojson = "0.24"
geoparquet = "0.5"
http-range-client = { version = "0.9", default-features = false }
object_store = "0.12"
serde_json = "1"
tempfile = "3"
thiserror = "1"
tokio = { version = "1.9", default-features = false }
wkb = "0.9"
wkt = "0.14"

[patch.crates-io]
geoarrow-array = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoarrow-schema = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoarrow-flatgeobuf = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoparquet = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
