[workspace]
members = ["geodatafusion"]
resolver = "2"

[workspace.package]
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
version = "0.5.1"
edition = "2024"
homepage = "https://geoarrow.org/geoarrow-rs/"
repository = "https://github.com/datafusion-contrib/datafusion-geo"
license = "MIT OR Apache-2.0"
keywords = ["python", "arrow", "geospatial"]
categories = ["wasm", "science::geo"]
rust-version = "1.85"

[workspace.dependencies]
datafusion = { git = "https://github.com/apache/datafusion", rev = "fa1f8c192dd531d3f2fca61885eafa3e9002f0dd" }
datafusion-ffi = { git = "https://github.com/apache/datafusion", rev = "fa1f8c192dd531d3f2fca61885eafa3e9002f0dd" }
geoarrow-schema = "0.5"
geodatafusion = { path = "../rust/geodatafusion" }
pyo3 = { version = "0.25", features = ["hashbrown", "serde", "anyhow"] }
serde_json = "1"
thiserror = "1"

[patch.crates-io]
geoarrow-array = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoarrow-schema = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoarrow-flatgeobuf = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
geoparquet = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "61a535b072766003ad06a4d7a25dcc15f010e68f" }
